// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("miniscaffold-docs-test-3")>]
[<assembly: AssemblyProductAttribute("miniscaffold-docs-test-3")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-01-28T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","13cb4baa288b72b038d542ba3569e8507366da46")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "miniscaffold-docs-test-3"
    let [<Literal>] AssemblyProduct = "miniscaffold-docs-test-3"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-01-28T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
    let [<Literal>] AssemblyInformationalVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "13cb4baa288b72b038d542ba3569e8507366da46"
