// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("miniscaffold-docs-test-3")>]
[<assembly: AssemblyProductAttribute("miniscaffold-docs-test-3")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-01-28T00:00:00.0000000-05:00")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","beta")>]
[<assembly: AssemblyMetadataAttribute("GitHash","a8bfae509602883067374755ecbbdb33d31a0e69")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "miniscaffold-docs-test-3"
    let [<Literal>] AssemblyProduct = "miniscaffold-docs-test-3"
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-01-28T00:00:00.0000000-05:00"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
    let [<Literal>] AssemblyInformationalVersion = "0.2.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "beta"
    let [<Literal>] AssemblyMetadata_GitHash = "a8bfae509602883067374755ecbbdb33d31a0e69"
